#!/usr/bin/env bash

NPM_SCRIPT=`find ./build/npm -wholename "*/bin/npm" -type l`

if [ ! -f "$NPM_SCRIPT" ]; then
    echo "Npm not found! Run gradle build first!"
else
    ./nodew $NPM_SCRIPT "$@"
fi

