#!/usr/bin/env bash

YARN_SCRIPT=`find ./build -wholename "*/bin/yarn" -type l`

if [ ! -f $YARN_SCRIPT ]; then
    echo "Yarn not found! Run gradle build first!"
else
    ./nodew $YARN_SCRIPT "$@"
fi

